name: Python package

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Lint
        run: make lint
      - name: Test with pytest
        run: make test
      - name: Test the Container Build
        run: make build
